---
name: checks
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4

      with:
        go-version: '1.24.0'

    - run: gofmt -s -d -e .

    - run: go test -cover ./...
