name: checks
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
jobs:
  check:
    runs-on: ubuntu-22.04
    container: golang:1.22
    steps:
    - uses: actions/checkout@v3
    - run: go vet -race ./...
    - run: go test -cover ./...
    - run: go build -buildvcs=false ./cmd/tpl && rm tpl
